#include "Core/editor_project_globals.h"
#include "Core/editor_project_storage.h"
#include "Core/image_lookup.h"
#include "Core/project_header.h"
#include "Core/viewer_save.h"
#include "Core/world_module_utils.h"
#include "UI/toast_notifications.h"
#include "compat.h"
#include "undo_manager.h"

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#include <windows.h>
#endif

static void mk2_export_path_join(char *out, size_t outsz, const char *dir, const char *file)
{
    if (!dir || !dir[0]) {
        snprintf(out, outsz, "%s", file ? file : "");
        return;
    }

    size_t len = strlen(dir);
    if (dir[len - 1] == '\\' || dir[len - 1] == '/')
        snprintf(out, outsz, "%s%s", dir, file ? file : "");
    else
        snprintf(out, outsz, "%s%c%s", dir, PATH_SEP_CHAR, file ? file : "");
}

static void mk2_export_ensure_directory(const char *path)
{
    if (!path || !path[0]) return;
#ifdef _WIN32
    CreateDirectoryA(path, NULL);
#else
    mkdir(path, 0755);
#endif
}

void export_mk2_assembly(void)
{
    if (!g_have_bdb || g_no == 0 || g_ni == 0) return;
    if (g_bdb_num_modules == 0) {
        undo_save_ex("Create Module");
        int ww = 0, wh = 0, md = 255, nm = 0, np = g_n_pals, no = g_no;
        char name[64] = "";
        if (sscanf(g_bdb_header, "%63s %d %d %d %d %d %d",
                   name, &ww, &wh, &md, &nm, &np, &no) < 7) {
            snprintf(name, sizeof name, "%s", g_name[0] ? g_name : "WORLD");
            ww = 1024; wh = 256;
        }
        int mod_x2 = (ww > 0 ? ww : 1024) - 1;
        int mod_y2 = (wh > 0 ? wh : 256) - 1;
        char line[256];
        snprintf(line, sizeof line, "MOD0 0 %d 0 %d", mod_x2, mod_y2);
        editor_project_set_single_module_line(line);
        snprintf(g_bdb_header, sizeof g_bdb_header, "%s %d %d %d %d %d %d",
                 name, ww, wh, md, g_bdb_num_modules, g_n_pals, g_no);
        g_dirty = 1;
    }
    sync_bdb_header_counts();

    size_t nlen = strlen(g_name);
    const char *suffix = (nlen >= 2) ? g_name + nlen - 2 : g_name;
    char hdrs_label[32], pals_label[32];
    snprintf(hdrs_label, sizeof hdrs_label, "%sHDRS", suffix);
    snprintf(pals_label, sizeof pals_label, "%sPALS", suffix);

    char outdir[520];
    snprintf(outdir, sizeof outdir, "%s", g_bdb_path);
    char *dot = strrchr(outdir, '.');
    if (dot) *dot = '\0';
    snprintf(outdir + strlen(outdir), sizeof(outdir) - strlen(outdir), "_MK2");
    mk2_export_ensure_directory(outdir);

    char package_path[520];
    char package_name[160];
    snprintf(package_name, sizeof package_name, "%s.BDB", g_name);
    mk2_export_path_join(package_path, sizeof package_path, outdir, package_name);
    bdb_save(package_path);
    snprintf(package_name, sizeof package_name, "%s.BDD", g_name);
    mk2_export_path_join(package_path, sizeof package_path, outdir, package_name);
    {
        char old_bdd_path[512];
        memcpy(old_bdd_path, g_bdd_path, sizeof old_bdd_path);
        snprintf(g_bdd_path, sizeof g_bdd_path, "%s", package_path);
        bdd_save();
        memcpy(g_bdd_path, old_bdd_path, sizeof g_bdd_path);
    }

    char equ_path[520];
    snprintf(package_name, sizeof package_name, "%s_EQU.H", g_name);
    mk2_export_path_join(equ_path, sizeof equ_path, outdir, package_name);
    FILE *equ_f = fopen(equ_path, "w");
    if (!equ_f) return;
    fprintf(equ_f, "; BGNDEQU.H - auto-generated by midway-bddtool\n");
    fprintf(equ_f, "; World: %s\n\n", g_name);
    fprintf(equ_f, "NUMIMGS\t\t.equ\t%d\n\n", g_ni);
    fprintf(equ_f, "NUMPALS\t\t.equ\t%d\n\n", g_n_pals);
    for (int m = 0; m < g_bdb_num_modules; m++) {
        int db = 0, sx = 0, sbb = 0, ssp = 0;
        char mn[64] = "";
        sscanf(g_bdb_modules[m], "%63s %d %d %d %d", mn, &db, &sx, &sbb, &ssp);
        if (mn[0]) {
            fprintf(equ_f, "%sBLKS\t\t.equ\t%d\n", mn, m);
            fprintf(equ_f, "%sBMOD\t\t.equ\t%d\n", mn, m);
        }
    }
    fclose(equ_f);

    char glo_path[520];
    snprintf(package_name, sizeof package_name, "%s_TBL.GLO", g_name);
    mk2_export_path_join(glo_path, sizeof glo_path, outdir, package_name);
    FILE *glo_f = fopen(glo_path, "w");
    if (!glo_f) return;
    fprintf(glo_f, "; BGNDTBL.GLO - auto-generated by midway-bddtool\n\n");
    fprintf(glo_f, "\t.global\t%s\n", hdrs_label);
    fprintf(glo_f, "\t.global\t%s\n\n", pals_label);
    for (int m = 0; m < g_bdb_num_modules; m++) {
        char mn[64] = "";
        sscanf(g_bdb_modules[m], "%63s", mn);
        if (mn[0]) {
            fprintf(glo_f, "\t.global\t%sBLKS\n", mn);
            fprintf(glo_f, "\t.global\t%sBMOD\n", mn);
        }
    }
    fprintf(glo_f, "\n\t.global\tENDMARKER\n");
    fclose(glo_f);

    int *obj_mod = (int *)malloc((size_t)g_no * sizeof(int));
    int *obj_order = (int *)malloc((size_t)g_no * sizeof(int));
    int *mod_objs = (int *)calloc((size_t)g_bdb_num_modules, sizeof(int));
    if (!obj_mod || !obj_order || !mod_objs) { free(obj_mod); free(obj_order); free(mod_objs); return; }
    for (int i = 0; i < g_no; i++) obj_order[i] = i;
    for (int i = 1; i < g_no; i++) {
        int tmp = obj_order[i];
        int j = i - 1;
        while (j >= 0 && g_obj[obj_order[j]].order > g_obj[tmp].order) {
            obj_order[j + 1] = obj_order[j];
            j--;
        }
        obj_order[j + 1] = tmp;
    }
    for (int i = 0; i < g_no; i++) {
        Img *im = img_find(g_obj[i].ii);
        obj_mod[i] = assign_module(g_obj[i].depth, g_obj[i].sy,
                                   im ? im->w : 1, im ? im->h : 1);
        if (obj_mod[i] >= 0) mod_objs[obj_mod[i]]++;
    }

    int *mod_min_x = (int *)malloc((size_t)g_bdb_num_modules * sizeof(int));
    int *mod_max_x = (int *)malloc((size_t)g_bdb_num_modules * sizeof(int));
    int *mod_min_y = (int *)malloc((size_t)g_bdb_num_modules * sizeof(int));
    int *mod_max_y = (int *)malloc((size_t)g_bdb_num_modules * sizeof(int));
    if (mod_min_x && mod_max_x && mod_min_y && mod_max_y) {
        for (int m = 0; m < g_bdb_num_modules; m++) {
            mod_min_x[m] = INT_MAX; mod_max_x[m] = INT_MIN;
            mod_min_y[m] = INT_MAX; mod_max_y[m] = INT_MIN;
        }
        for (int i = 0; i < g_no; i++) {
            int m = obj_mod[i]; if (m < 0) continue;
            Img *im = img_find(g_obj[i].ii);
            if (!im) continue;
            int x1 = g_obj[i].depth, x2 = x1 + im->w;
            int y1 = g_obj[i].sy, y2 = y1 + im->h;
            if (x1 < mod_min_x[m]) mod_min_x[m] = x1;
            if (x2 > mod_max_x[m]) mod_max_x[m] = x2;
            if (y1 < mod_min_y[m]) mod_min_y[m] = y1;
            if (y2 > mod_max_y[m]) mod_max_y[m] = y2;
        }
    }

    unsigned short *ctrl = (unsigned short *)malloc((size_t)g_ni * sizeof(unsigned short));
    if (ctrl) {
        for (int i = 0; i < g_ni; i++) {
            Img *im = &g_img[i];
            if (!im->pix || im->w == 0 || im->h == 0) { ctrl[i] = 0; continue; }
            Uint8 max_pix = 0;
            for (int py = 0; py < im->h; py++)
                for (int px = 0; px < im->w; px++)
                    if (im->pix[py * im->w + px] > max_pix)
                        max_pix = im->pix[py * im->w + px];
            int bpp = 0;
            if (max_pix <= 1) bpp = 1;
            else if (max_pix < 4) bpp = 2;
            else if (max_pix < 8) bpp = 3;
            else if (max_pix < 16) bpp = 4;
            else if (max_pix < 32) bpp = 5;
            else if (max_pix < 64) bpp = 6;
            else if (max_pix < 128) bpp = 7;
            else bpp = 8;
            ctrl[i] = (unsigned short)((bpp & 0xF) << 12);
            ctrl[i] |= 0x0040;
        }
    }

    char asm_path[520];
    snprintf(package_name, sizeof package_name, "%s_TBL.ASM", g_name);
    mk2_export_path_join(asm_path, sizeof asm_path, outdir, package_name);
    FILE *asm_f = fopen(asm_path, "w");
    if (asm_f) {
        fprintf(asm_f, "; BGNDTBL.ASM skeleton - auto-generated by midway-bddtool\n");
        fprintf(asm_f, "; Inspection/export aid only. LOAD2 remains authoritative for compression, dedup, and final addresses.\n");
        fprintf(asm_f, "; World: %s  Objects: %d  Images: %d  Palettes: %d\n\n", g_name, g_no, g_ni, g_n_pals);

        fprintf(asm_f, "%s:\n", hdrs_label);
        for (int i = 0; i < g_ni; i++) {
            Img *im = &g_img[i];
            unsigned short c = ctrl ? ctrl[i] : 0;
            char comment[64] = "";
            if (i == 0) snprintf(comment, sizeof comment, "\t;x size, y size");
            fprintf(asm_f, "\t.word\t%d,%d%s\n", im->w, im->h, comment);
            fprintf(asm_f, "\t.long\t0%XH\t\t;address\n", im->idx);
            snprintf(comment, sizeof comment, ";dma ctrl");
            fprintf(asm_f, "\t.word\t0%04XH%s\n", c, comment);
        }
        fprintf(asm_f, "\n");

        for (int m = 0; m < g_bdb_num_modules; m++) {
            char mn[64] = "";
            sscanf(g_bdb_modules[m], "%63s", mn);
            if (!mn[0]) continue;
            fprintf(asm_f, "%sBLKS:\n", mn);
            int first = 1;
            for (int oi = 0; oi < g_no; oi++) {
                int i = obj_order[oi];
                if (obj_mod[i] != m) continue;
                Obj *o = &g_obj[i];
                int hdr_idx = 0;
                for (int hi = 0; hi < g_ni; hi++)
                    if (g_img[hi].idx == o->ii) { hdr_idx = hi; break; }
                int wx_out = (o->wx & 0xFFF0) | 0x0040 | (o->fl & 0xF);
                int hdr_word = (hdr_idx & 0x0FFF) | ((o->fl & 0xF0) << 8);
                if (first) {
                    fprintf(asm_f, "\t.word\t0%04XH\t\t;flags\n", wx_out);
                    fprintf(asm_f, "\t.word\t%d,%d\t\t;x,y\n", o->depth, o->sy);
                    fprintf(asm_f, "\t.word\t0%04XH\t\t;pal7-4,hdr11-0\n", hdr_word);
                    first = 0;
                } else {
                    fprintf(asm_f, "\t.word\t0%04XH,%d,%d,0%04XH\n", wx_out, o->depth, o->sy, hdr_word);
                }
            }
            fprintf(asm_f, "\t.word\t0FFFFH\t\t;End Marker\n\n");
        }

        for (int m = 0; m < g_bdb_num_modules; m++) {
            char mn[64] = "";
            sscanf(g_bdb_modules[m], "%63s", mn);
            if (!mn[0]) continue;
            int bw = 0, bh = 0;
            if (mod_min_x && mod_max_x) bw = mod_max_x[m] - mod_min_x[m];
            if (mod_min_y && mod_max_y) bh = mod_max_y[m] - mod_min_y[m];
            if (bw < 0) bw = 0; if (bh < 0) bh = 0;
            fprintf(asm_f, "%sBMOD:\n", mn);
            fprintf(asm_f, "\t.word\t%d,%d,%d\t\t;x size, y size, #blocks\n", bw, bh, mod_objs ? mod_objs[m] : 0);
            fprintf(asm_f, "\t.long\t%sBLKS, %s, %s\n\n", mn, hdrs_label, pals_label);
        }

        fprintf(asm_f, "ENDMARKER:\n");
        fclose(asm_f);
    }

    char pal_path[520];
    snprintf(package_name, sizeof package_name, "%s_PAL.ASM", g_name);
    mk2_export_path_join(pal_path, sizeof pal_path, outdir, package_name);
    FILE *pal_f = fopen(pal_path, "w");
    if (pal_f) {
        fprintf(pal_f, "; BGNDPAL.ASM - auto-generated by midway-bddtool\n\n");
        fprintf(pal_f, "%s:\n", pals_label);
        for (int pi = 0; pi < g_n_pals; pi++) {
            fprintf(pal_f, "\t.word\t");
            int pc = g_pal_count[pi];
            for (int ci = 0; ci < pc; ci++) {
                Uint32 c = g_pals[pi][ci];
                unsigned short w = (unsigned short)(((c >> 19) & 0x1F) << 10)
                                 | (unsigned short)(((c >> 11) & 0x1F) << 5)
                                 | (unsigned short)((c >> 3) & 0x1F);
                if (ci == 0) w = 0;
                fprintf(pal_f, "0%04XH", w);
                if (ci < pc - 1) fputc(',', pal_f);
                if (ci > 0 && ci % 10 == 0) fprintf(pal_f, "\n\t.word\t");
            }
            fprintf(pal_f, "\n");
        }
        fclose(pal_f);
    }

    free(obj_mod); free(obj_order); free(mod_objs);
    free(mod_min_x); free(mod_max_x); free(mod_min_y); free(mod_max_y);
    free(ctrl);

    char lod_path[520];
    snprintf(package_name, sizeof package_name, "%s.LOD", g_name);
    mk2_export_path_join(lod_path, sizeof lod_path, outdir, package_name);
    FILE *lod_f = fopen(lod_path, "w");
    if (lod_f) {
        fprintf(lod_f, "; %s standalone BLIMP background load\n", g_name);
        fprintf(lod_f, "; Copy %s.BDB and %s.BDD beside this file before running LOAD2.\n", g_name, g_name);
        fprintf(lod_f, "; Address below mirrors the current mk2-main ORNGBL video-ROM test slot.\n");
        fprintf(lod_f, "***> 5d40000\n");
        fprintf(lod_f, "ZON>\n");
        fprintf(lod_f, "PPP> 8\n");
        fprintf(lod_f, "ASM> %s.TBL\n", g_name);
        fprintf(lod_f, "GLO> %s.GLO\n", g_name);
        fprintf(lod_f, "BBB> %s\n", g_name);
        fclose(lod_f);
    }

    char readme_path[520];
    mk2_export_path_join(readme_path, sizeof readme_path, outdir, "README.txt");
    FILE *rm_f = fopen(readme_path, "w");
    if (rm_f) {
        fprintf(rm_f, "MK2 Background Assembly Skeleton: %s\n", g_name);
        fprintf(rm_f, "======================================\n");
        fprintf(rm_f, "\nGenerated by midway-bddtool\n\n");
        fprintf(rm_f, "Important:\n");
        fprintf(rm_f, "  This export is a readable inspection skeleton, not a replacement for LOAD2.\n");
        fprintf(rm_f, "  It preserves module assignment rules and full palette-index encoding, but it does not reproduce LOAD2 compression, checksum dedup, or final video-ROM placement.\n");
        fprintf(rm_f, "  For playable MK2 builds, use the Stage Kit/LOAD2 promotion path and treat LOAD2 output as authoritative.\n\n");
        fprintf(rm_f, "Files:\n");
        fprintf(rm_f, "  %s.BDB        - Object placement data\n", g_name);
        fprintf(rm_f, "  %s.BDD        - Image & palette data\n", g_name);
        fprintf(rm_f, "  %s_EQU.H      - Assembly equates\n", g_name);
        fprintf(rm_f, "  %s_TBL.GLO    - Global symbols\n", g_name);
        fprintf(rm_f, "  %s_TBL.ASM    - Readable assembly skeleton (HDRS/BLKS/BMOD)\n", g_name);
        fprintf(rm_f, "  %s_PAL.ASM    - Palette data\n", g_name);
        fprintf(rm_f, "  %s.LOD        - LOAD2 template with BBB> %s\n", g_name, g_name);
        fprintf(rm_f, "\nStats:\n");
        fprintf(rm_f, "  Objects: %d\n", g_no);
        fprintf(rm_f, "  Images:  %d\n", g_ni);
        fprintf(rm_f, "  Palettes: %d\n", g_n_pals);
        fprintf(rm_f, "  Modules: %d\n", g_bdb_num_modules);
        fprintf(rm_f, "\nBDB/BDD smoke-test values:\n");
        fprintf(rm_f, "  Header:  NAME 400 254 255 1 1 1\n");
        fprintf(rm_f, "  Module:  MOD 0 399 0 253  (inclusive full visible MK2 screen rectangle)\n");
        fprintf(rm_f, "  Object:  4000 0 0 1 0      (play layer, top-left corner, image 1, palette 0)\n");
        if (strlen(g_name) > 8) {
            fprintf(rm_f, "\nName warning:\n");
            fprintf(rm_f, "  '%s' is longer than the DOS 8.3 base-name limit used by LOAD2.\n", g_name);
            fprintf(rm_f, "  Rename the BDB/BDD/LOD base to 8 characters or less before importing.\n");
        }
        fprintf(rm_f, "\nCurrent mk2-main integration notes:\n");
        fprintf(rm_f, "  1. Put %s.BDB and %s.BDD in mk2-main/data.\n", g_name, g_name);
        fprintf(rm_f, "  2. Add or replace a LOAD2 LOD entry with: BBB> %s\n", g_name);
        fprintf(rm_f, "  3. For an isolated test, use the generated %s.LOD template.\n", g_name);
        fprintf(rm_f, "  4. The template starts at ***> 5d40000, matching the current ORNGBL test slot.\n");
        fprintf(rm_f, "  5. Run build.py so LOAD2 refreshes generated tables, then promote/merge the resulting BGNDTBL/BGNDPAL symbols used by BGND.ASM.\n");
        fprintf(rm_f, "\nROM-space caution:\n");
        fprintf(rm_f, "  Background BBB data is image/video data. In current mk2-main, ORNGBL uses video-ROM address 0x05D40000.\n");
        fprintf(rm_f, "  Program-ROM REVX space (0xFFD00000+) is used there for custom sprite IRWs, not as the default background BBB slot.\n\n");
        fclose(rm_f);
    }

    fprintf(stderr, "export: MK2 export written to %s/\n", outdir);
    char toast[128];
    snprintf(toast, sizeof toast, "Exported to %s/", g_name);
    stage_set_toast(toast);
}
